import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * KOSMOS Documentation Sidebar Configuration
 * Using autogenerated sidebars for now to ensure all 232 files are included
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar - autogenerated from file structure
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from docs directory
    },
  ],

  // API sidebar (auto-generated from OpenAPI)
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

export default sidebars;
